baseURL = "/"
languageCode = "pt-BR"
title = "O Caminhar"
theme = "mediumish-gohugo-theme"
summaryLength = 10
copyright = "Vera Oliveira - All rights reserved"
enableEmoji = true
publishDir = "docs"
#disqusShortname = "your-shortname-here"
#googleAnalytics = "UA-1XXXXXXX1-1"

[params]
  logo = "/images/logo.png"
  description ="Viajando com a Vera!"
  #mailchimp = "you can provide a mailchimp-link here"

[params.author]
  name = "Vera Oliveira"
  thumbnail = "/images/author.png"
  description = "Peregrina deste blog."

[params.index]
  picture = "/images/foto.jpg"
  title = "Vera Oliveira"
  subtitle = "Peregrina, Artesã, Mestre REIKI!"
  mdtext = '''
Blog Pessoal com detalhes de cursos, viagens e mandalas!\
**Venha comigo por este caminho de vida plena.**\
### O Caminhar
'''
  alertbar = false

[params.social]
  facebook = "reikivera"
  linkedin = "vera-lucia-de-oliveira-32100315b"
  instagram = "veralucia.oliveira63"

## Main Menu
[[menu.main]]
    name = "Blog"
    weight = 100
    identifier = "blog"
    url = "/blog"
[[menu.main]]
    name = "Sobre mim"
    identifier = "about"
    weight = 200
    url = "/"
