baseURL = "/"
copyright = "Vera Oliveira - All rights reserved"
enableEmoji = true
languageCode = "pt-BR"
publishDir = "docs"
summaryLength = 10
theme = "mediumish-gohugo-theme"
title = "O Caminhar"
[[menu.main]]
identifier = "blog"
name = "Blog"
url = "/blog"
weight = 100
[[menu.main]]
identifier = "about"
name = "Sobre mim"
url = "/"
weight = 200
[params]
description = "Viajando com a Vera!"
logo = "/images/logo.png"
[params.author]
description = "Peregrina deste blog."
name = "Vera Oliveira"
thumbnail = "/images/author.png"
[params.index]
alertbar = false
mdtext = "'''\nBlog Pessoal com detalhes de cursos, viagens e mandalas!\\\n**Venha comigo por este caminho de vida plena.**\\\n### [O Caminhar]\n'''\n"
picture = "/images/foto.jpg"
subtitle = "Peregrina, Artesã, Mestre REIKI!"
title = "Vera Oliveira"
[params.social]
facebook = "reikivera"
instagram = "veralucia.oliveira63"
linkedin = "vera-lucia-de-oliveira-32100315b"
